-- AlterTable
ALTER TABLE "User" ALTER COLUMN "last_sign_in_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "update_at" SET DEFAULT CURRENT_TIMESTAMP;
